//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteUpdater.Sender.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteUpdater.Sender.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new files.
        /// </summary>
        public static string Btn_AddNewFiles {
            get {
                return ResourceManager.GetString("Btn_AddNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all files.
        /// </summary>
        public static string Btn_RemoveAllFiles {
            get {
                return ResourceManager.GetString("Btn_RemoveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string Btn_RemoveFile {
            get {
                return ResourceManager.GetString("Btn_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send files.
        /// </summary>
        public static string Btn_SendFiles {
            get {
                return ResourceManager.GetString("Btn_SendFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all files.
        /// </summary>
        public static string CMenue_DelslectAllFiles {
            get {
                return ResourceManager.GetString("CMenue_DelslectAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect choosen file(s).
        /// </summary>
        public static string CMenue_DeselectChoosenFiles {
            get {
                return ResourceManager.GetString("CMenue_DeselectChoosenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all files.
        /// </summary>
        public static string CMenue_RemoveAllFiles {
            get {
                return ResourceManager.GetString("CMenue_RemoveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove choosen file(s).
        /// </summary>
        public static string CMenue_RemoveSelectedFiles {
            get {
                return ResourceManager.GetString("CMenue_RemoveSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all files.
        /// </summary>
        public static string CMenue_SelectAllFiles {
            get {
                return ResourceManager.GetString("CMenue_SelectAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select choosen file(s).
        /// </summary>
        public static string CMenue_SelectChoosenFiles {
            get {
                return ResourceManager.GetString("CMenue_SelectChoosenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to establish a connection to the Receiver.
        /// </summary>
        public static string Error_ConnectionNotPossible {
            get {
                return ResourceManager.GetString("Error_ConnectionNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while sending files..
        /// </summary>
        public static string Error_WhileSendingFiles {
            get {
                return ResourceManager.GetString("Error_WhileSendingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File selection.
        /// </summary>
        public static string FileDialog_Title {
            get {
                return ResourceManager.GetString("FileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update:.
        /// </summary>
        public static string Lbl_AutoUpdate {
            get {
                return ResourceManager.GetString("Lbl_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update delay:.
        /// </summary>
        public static string Lbl_AutoUpdateDelay {
            get {
                return ResourceManager.GetString("Lbl_AutoUpdateDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to front on error:.
        /// </summary>
        public static string Lbl_BringToFrontOnError {
            get {
                return ResourceManager.GetString("Lbl_BringToFrontOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection-Status:.
        /// </summary>
        public static string Lbl_ConnectionSatus {
            get {
                return ResourceManager.GetString("Lbl_ConnectionSatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote-Updater Reciever IP Address:.
        /// </summary>
        public static string Lbl_IpReceiver {
            get {
                return ResourceManager.GetString("Lbl_IpReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote-Updater Receiver Port:.
        /// </summary>
        public static string Lbl_PortReceiver {
            get {
                return ResourceManager.GetString("Lbl_PortReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote-Updater Sender.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferabel files.
        /// </summary>
        public static string Tab_TransferableFiles {
            get {
                return ResourceManager.GetString("Tab_TransferableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Files.
        /// </summary>
        public static string ToolTip_AddNewFiles {
            get {
                return ResourceManager.GetString("ToolTip_AddNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all files.
        /// </summary>
        public static string ToolTip_RemoveAllFiles {
            get {
                return ResourceManager.GetString("ToolTip_RemoveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string ToolTip_RemoveFile {
            get {
                return ResourceManager.GetString("ToolTip_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected with .
        /// </summary>
        public static string Txt_ConnectionStatusConnected {
            get {
                return ResourceManager.GetString("Txt_ConnectionStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string Txt_ConnectionStatusNotConnected {
            get {
                return ResourceManager.GetString("Txt_ConnectionStatusNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Txt_ConnectionStatusUnknown {
            get {
                return ResourceManager.GetString("Txt_ConnectionStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Txt_Error {
            get {
                return ResourceManager.GetString("Txt_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all files.
        /// </summary>
        public static string Txt_SelectAllFiles {
            get {
                return ResourceManager.GetString("Txt_SelectAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string Unit_Seconds {
            get {
                return ResourceManager.GetString("Unit_Seconds", resourceCulture);
            }
        }
    }
}
