//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartStopWindowsService.Plugin.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartStopWindowsService.Plugin.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Service Name.
        /// </summary>
        internal static string Txt_DefaultWindowsServiceDescription {
            get {
                return ResourceManager.GetString("Txt_DefaultWindowsServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExampleService.
        /// </summary>
        internal static string Txt_DefaultWindowsServiceName {
            get {
                return ResourceManager.GetString("Txt_DefaultWindowsServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action starts a Windows-Service.
        /// </summary>
        internal static string Txt_StarterActionDescription {
            get {
                return ResourceManager.GetString("Txt_StarterActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Service Starter.
        /// </summary>
        internal static string Txt_StarterActionName {
            get {
                return ResourceManager.GetString("Txt_StarterActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action stopps a Windows-Service.
        /// </summary>
        internal static string Txt_StopperActionDescription {
            get {
                return ResourceManager.GetString("Txt_StopperActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-Service Stopper.
        /// </summary>
        internal static string Txt_StopperActionName {
            get {
                return ResourceManager.GetString("Txt_StopperActionName", resourceCulture);
            }
        }
    }
}
